package com.tasktracker.app.model;

public enum Endpoint {
    GETTASKS,
    GETTASKBYID,
    CREATETASK,
    DELETETASK,
    DELETETASKS,
    GETSUBTASKS,
    CREATESUBTASK,
    CREATESUBTASK_ID,
    DELETESUBTASKS,
    DELETESUBTASK,
    GETEPICS,
    GETEPIC_ID,
    GETEPICSUBTASKS,
    CREATEEPIC,
    DELETEEPICS,
    DELETEEPIC,
    GETHISTORY,
    GETPRIORITYTASKS,
    UNKNOWN
}
